{
  "type": "record",
  "name": "HcmSinkResponse",
  "namespace": "com.standardinsurance.eoi",
  "fields": [
    { "name": "http_status_code",    "type": ["null", "string"], "default": null },
    { "name": "http_status_message", "type": ["null", "string"], "default": null },
    { "name": "response_body",       "type": ["null", "string"], "default": null },
    { "name": "error_code",          "type": ["null", "string"], "default": null },
    { "name": "error_message",       "type": ["null", "string"], "default": null },
    { "name": "retry_count",         "type": ["null", "string"], "default": null },
    { "name": "original_topic",      "type": ["null", "string"], "default": null },
    { "name": "original_partition",  "type": ["null", "string"], "default": null },
    { "name": "original_offset",     "type": ["null", "string"], "default": null },
    { "name": "correlation_id",      "type": ["null", "string"], "default": null },
    { "name": "group_id",            "type": ["null", "string"], "default": null },
    { "name": "event_type",          "type": ["null", "string"], "default": null },
    { "name": "worker_id",           "type": ["null", "string"], "default": null },
    { "name": "timestamp",           "type": ["null", "string"], "default": null }
  ]
}
